export const CHECK_ROOM_BOOKING_REQUEST = "CHECK_ROOM_BOOKING_REQUEST";
export const CHECK_ROOM_BOOKING_SUCCESS = "CHECK_ROOM_BOOKING_SUCCESS";
export const CHECK_ROOM_BOOKING_FAIL = "CHECK_ROOM_BOOKING_FAIL";
export const CHECK_ROOM_BOOKING_RESET = "CHECK_ROOM_BOOKING_RESET";

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";
export const CREATE_BOOKING_RESET = "CREATE_BOOKING_RESET";