export const CHECK_ROOM_BOOKING_REQUEST = "CHECK_ROOM_BOOKING_REQUEST";
export const CHECK_ROOM_BOOKING_SUCCESS = "CHECK_ROOM_BOOKING_SUCCESS";
export const CHECK_ROOM_BOOKING_FAIL = "CHECK_ROOM_BOOKING_FAIL";