export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAIL = "FETCH_ROOMS_FAIL";

export const ROOM_DETAILS_REQUEST = "ROOM_DETAILS_REQUEST";
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";

export const ROOM_CREATE_REVIEW_REQUEST = "ROOM_CREATE_REVIEW_REQUEST";
export const ROOM_CREATE_REVIEW_SUCCESS = "ROOM_CREATE_REVIEW_SUCCESS";
export const ROOM_CREATE_REVIEW_FAIL = "ROOM_CREATE_REVIEW_FAIL";